-
  type: cohesion_component
  export:
    uuid: 4cc12444-8b81-4a7b-b9ac-8e521c021ed2
    langcode: en
    status: true
    dependencies: {  }
    id: cpt_webform
    label: Webform
    json_values: '{"canvas":[{"type":"container","uid":"container","title":"Container","status":{"collapsed":false},"uuid":"a4234b74-49db-4652-8c3c-907dd8998c3d","parentUid":"root","isContainer":true,"children":[{"type":"item","uid":"site_studio_webform_element","isCustom":true,"title":"Webform Element","selected":false,"status":{"collapsed":true},"uuid":"e823cd77-768e-4a7d-b8bd-6720f3606c1e","parentUid":"container","isContainer":false,"children":[]}]}],"componentForm":[{"type":"form-container","uid":"form-section","title":"Field group","status":{"collapsed":false},"options":{"formBuilder":true},"uuid":"4752c341-b950-4590-a3e3-7dcf7ad84450","parentUid":"root","isContainer":true,"children":[{"type":"form-field","uid":"form-input","title":"Input","translate":true,"status":{"collapsed":false},"uuid":"b2663e43-a1af-4a4b-972f-484258ee0c61","parentUid":"form-section","isContainer":false,"children":[]}]}],"mapper":{"a4234b74-49db-4652-8c3c-907dd8998c3d":{},"e823cd77-768e-4a7d-b8bd-6720f3606c1e":{"settings":{"formDefinition":[{"formKey":"site_studio_webform_element_settings","children":[{"formKey":"site_studio_webform_element_dynamic","breakpoints":[],"activeFields":[{"name":"webform_id","active":true}]}]}],"selectorType":"topLevel","form":null,"items":[]}}},"model":{"a4234b74-49db-4652-8c3c-907dd8998c3d":{"settings":{"width":"fluid"}},"e823cd77-768e-4a7d-b8bd-6720f3606c1e":{"settings":{"title":"Webform Element","webform_id":"[field.b2663e43-a1af-4a4b-972f-484258ee0c61]"},"context-visibility":{"contextVisibility":{"condition":"ALL"}},"styles":{"settings":{"element":"site_studio_webform_element"}}},"4752c341-b950-4590-a3e3-7dcf7ad84450":{"settings":{"type":"cohSection","title":"Field group","hideRowHeading":0,"removePadding":0,"columnCount":"coh-component-field-group-1-col","breakpointIcon":"","breakpoints":false,"propertiesMenu":false,"disableScrollbar":true,"disableEllipsisMenu":true,"isOpen":true}},"b2663e43-a1af-4a4b-972f-484258ee0c61":{"settings":{"title":"Webform ID","schema":{"type":"string","escape":true,"required":true},"machineName":"webform-id","tooltipPlacement":"auto right"},"contextVisibility":{"condition":"ALL"}}},"previewModel":{"b2663e43-a1af-4a4b-972f-484258ee0c61":{},"e823cd77-768e-4a7d-b8bd-6720f3606c1e":{}},"variableFields":{"b2663e43-a1af-4a4b-972f-484258ee0c61":[],"e823cd77-768e-4a7d-b8bd-6720f3606c1e":["settings.webform_id"]},"meta":{"fieldHistory":[{"uuid":"b2663e43-a1af-4a4b-972f-484258ee0c61","type":"form-input","machineName":"webform-id"}]}}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0029
    locked: false
    modified: true
    selectable: true
    category: cpt_cat_general_components
    preview_image: {  }
    has_quick_edit: true
    entity_type_access: {  }
    bundle_access: {  }
    twig_template: component--cohesion-cpt-webform
    weight: 0
-
  type: cohesion_component_category
  export:
    uuid: f0745755-460f-41c6-a9f9-a67e82e788c4
    langcode: en
    status: true
    dependencies: {  }
    _core:
      default_config_hash: uD3bsqk6dEY_k5T4rq3k_rgjNjR_BC3IXrfvj9t3SKk
    id: cpt_cat_general_components
    label: 'General components'
    json_values: '{}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0029
    locked: false
    modified: false
    selectable: true
    class: category-3
    weight: -10
